apiVersion: v1
kind: Service
metadata:
  name: kubservice
spec:
  selector:
    app: firstapp
  ports:
    - port: 2525
      name: mainappport
      targetPort: 5000
    - port: 2526
      name: testappport
      targetPort: 8089
  type: LoadBalancer